# Dockerfile.dev
FROM node:20-alpine

RUN apk add --no-cache --virtual .build-deps curl \
  && curl -f https://get.pnpm.io/v6.js | node - add --global pnpm \
  && apk del .build-deps

WORKDIR /home/node/app

COPY package*.json ./
COPY pnpm-lock.yaml ./

RUN pnpm install

RUN npx prisma generate

COPY . .

CMD ["pnpm", "dev"]